{% set name = "meteoserver" %}
{% set version = "0.0.17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MarcvdSluys/Meteoserver/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 869b153f04f8761539a9d2aab1f53cc9cc6f2c271a7d9c367f50b958f8e8e799
  patches:
    - install_modules.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6,<3.12
    - setuptools >=61.0
    - pip
  run:
    - python >=3.6,<3.12
    - pandas
    - requests

test:
  imports:
    - meteoserver
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/MarcvdSluys/Meteoserver
  summary: A Python module to obtain and read Dutch weather data from Meteoserver.nl
  license: GPL-3.0-or-later
  license_file: LICENCE

extra:
  recipe-maintainers:
    - ocefpaf
