{% set name = "meteoserver" %}
{% set version = "0.0.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MarcvdSluys/Meteoserver/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 1b77a7a79abf6569deb7948a6057c6142b5645453e3f517e962753fe9127648f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
  run:
    - python >={{ python_min }}
    - pandas
    - requests

test:
  imports:
    - meteoserver
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/MarcvdSluys/Meteoserver
  summary: A Python module to obtain and read Dutch weather data from Meteoserver.nl
  license: GPL-3.0-or-later
  license_file: LICENCE

extra:
  recipe-maintainers:
    - ocefpaf
